
#define UTF8_ENCODING_LIB_TO_STRING(x)    #x

#define UTF8_ENCODING_LIB_MAJOR_VERSION   @PROJECT_MAJOR_VERSION@
#define UTF8_ENCODING_LIB_MINOR_VERSION   @PROJECT_MINOR_VERSION@
#define UTF8_ENCODING_LIB_PATCH_VERSION   @PROJECT_PATCH_VERSION@

#define UTF8_ENCODING_LIB_VERSION \
    UTF8_ENCODING_LIB_TO_STRING(UTF8_ENCODING_LIB_MAJOR_VERSION) "." \
    UTF8_ENCODING_LIB_TO_STRING(UTF8_ENCODING_LIB_MINOR_VERSION) "." \
    UTF8_ENCODING_LIB_TO_STRING(UTF8_ENCODING_LIB_PATCH_VERSION)
